# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/Codes/Vivado/2016/single/single.srcs/sources_1/ip/DR/DR.xci
# IP: The module: 'DR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Codes/Vivado/2016/single/single.srcs/sources_1/ip/DR/DR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DR'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/Codes/Vivado/2016/single/single.srcs/sources_1/ip/DR/DR.xci
# IP: The module: 'DR' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Codes/Vivado/2016/single/single.srcs/sources_1/ip/DR/DR_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'DR'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
